### PR TITLE
fix: show market creator instead of fpmm contract on market activity

### LINKED ISSUE #113: The address of the owner of the first liquidity transaction is incorrect
For initial liquidity-adding transactions on markets on Presagio, it always shows the address responsible as https://gnosisscan.io/address/0x9083a2b699c0a4ad06f63580bde2635d26a3eef0

e.g. for this market here: https://presagio.pages.dev/markets?id=0x03f8d8667d83a434d174a3616fd4667ffffbdc92 there are 3 liquidity transactions.

Screenshot 2024-10-09 at 09 50 05

But this is the FPMM contract address. The market creator in this case is actually `0xffc8029154ecd55abed15bd428ba596e7d23f557`

Using the graph explorer for this market https://thegraph.com/explorer/subgraphs/9fUVQpFwzpdWS9bq5WkAnmKbNNcoBwatMR4yZq81pbbz?view=Query&chain=arbitrum-one

```
{
  fpmmTransactions(
    where: {fpmmType: Liquidity, fpmm_: {id: "0x03f8d8667d83a434d174a3616fd4667ffffbdc92"}}
  ) {
    fpmm {
      creator
    }
    user {
      id
    }
  }
}
```

gives the response

```
{
  "data": {
    "fpmmTransactions": [
      {
        "fpmm": {
          "creator": "0xffc8029154ecd55abed15bd428ba596e7d23f557"
        },
        "user": {
          "id": "0x24ff9962b7d859d5e51ced04c594c474b2301a1c"
        }
      },
      {
        "fpmm": {
          "creator": "0xffc8029154ecd55abed15bd428ba596e7d23f557"
        },
        "user": {
          "id": "0x24ff9962b7d859d5e51ced04c594c474b2301a1c"
        }
      },
      {
        "fpmm": {
          "creator": "0xffc8029154ecd55abed15bd428ba596e7d23f557"
        },
        "user": {
          "id": "0x9083a2b699c0a4ad06f63580bde2635d26a3eef0"
        }
      }
    ]
  }
}
```

so it looks like the correct behaviour should be:
- for the first liquidity transaction use `transaction.fpmm.creator`
- but for the rest take `transaction.user.id`

### PR DESCRIPTION
**Pull request by berteotti**
image

image

Closes #113

### CODE REVIEW

File: app/markets/MarketActivity.tsx [hunk 1]
```diff
@@ -243,8 +243,13 @@ interface LiquidityEventRowProps {
   isAIAgent: boolean;
 }
 
+const FPMMContractAddress = '0x9083a2b699c0a4ad06f63580bde2635d26a3eef0';
```
Comment (Diogomartf) [inline app/markets/MarketActivity.tsx:246]: I think this should be on constants.

**Review by Diogomartf — APPROVED** [review]

File: app/markets/MarketActivity.tsx (hunk 1 above)
Comment (berteotti) [reply app/markets/MarketActivity.tsx:246]: For now I think it's good.
